version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: real_time_quizz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "5050:80"
    depends_on:
      - mysql

  redis:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis:/data

  core-dynamic-quizz:
    build: ./packages/core-dynamic-quizz
    container_name: core_dynamic_quizz
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis-db
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./packages/core-dynamic-quizz:/app

  office-dynamic-quizz:
    build: ./packages/office-dynamic-quizz
    container_name: office_dynamic_quizz
    environment:
      NEXT_PUBLIC_SERVER_URL: http://core-dynamic-quizz:5000
    ports:
      - "3000:3000"
    depends_on:
      - core-dynamic-quizz

volumes:
  mysql_data:
  redis:
    driver: local
