version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: real_time_quizz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "5050:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
