version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""  
      MYSQL_DATABASE: real_time_quizz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT:  3306
    ports:
      - "5050:80"
    depends_on:
      - mysql

  redis:
    container_name: redis-db
    image: redis
    environment:
      - REDIS_PORT=6379
    ports:
      -  6379:6379
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis:/data

  backend:
    build:
      context: .
      dockerfile: packages/core-dynamic-quizz/Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    networks:
      - backend_network
    depends_on:
      - mysql
      - redis
    volumes:
      - ./packages/core-dynamic-quizz:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: packages/office-dynamic-quizz/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - backend_network
    depends_on:
      - backend
    volumes:
      - ./packages/office-dynamic-quizz:/app
      - /app/node_modules

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
  redis:
    driver: local
