version: '3.8'
services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  core-dynamic-quizz:
    build: ./packages/core-dynamic-quizz
    ports:
      - "8000:8000"
    volumes:
      - ./packages/core-dynamic-quizz:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/dunamicquizz
    depends_on:
      - mongo

  office-dynamic-quizz:
    build: ./packages/office-dynamic-quizz
    ports:
      - "3000:3000"
    volumes:
      - ./packages/office-dynamic-quizz:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  mongo-data:
