name: Hadolint
on:
  pull_request:
  push:
jobs:
  hadolint-core:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: packages/core-dynamic-quizz/Dockerfile
  hadolint-office:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: packages/office-dynamic-quizz/Dockerfile
